backend:
  name: git-gateway
  branch: main  # or your repo's default branch

media_folder: "docs/assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
